# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_AboutMe(object):
    def setupUi(self, mw_AboutMe):
        mw_AboutMe.setObjectName("mw_AboutMe")
        mw_AboutMe.resize(200, 200)
        mw_AboutMe.setMinimumSize(QtCore.QSize(200, 200))
        mw_AboutMe.setMaximumSize(QtCore.QSize(200, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/favicon/images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mw_AboutMe.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mw_AboutMe)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(25, 0, 150, 150))
        self.graphicsView.setStyleSheet("border-image: url(:/images/images/Logo.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 150, 100, 25))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setStyleSheet("color: rgb(0, 0, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 170, 200, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        mw_AboutMe.setCentralWidget(self.centralwidget)

        self.retranslateUi(mw_AboutMe)
        QtCore.QMetaObject.connectSlotsByName(mw_AboutMe)

    def retranslateUi(self, mw_AboutMe):
        _translate = QtCore.QCoreApplication.translate
        mw_AboutMe.setWindowTitle(_translate("mw_AboutMe", "About Me"))
        self.label.setText(_translate("mw_AboutMe", "Gürkan KARADAĞ"))
        self.label_2.setText(_translate("mw_AboutMe", "Instagram Auto DM GUI v1.0"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw_AboutMe = QtWidgets.QMainWindow()
    ui = Ui_mw_AboutMe()
    ui.setupUi(mw_AboutMe)
    mw_AboutMe.show()
    sys.exit(app.exec_())
