# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_AddAccount(object):
    def setupUi(self, mw_AddAccount):
        mw_AddAccount.setObjectName("mw_AddAccount")
        mw_AddAccount.resize(290, 360)
        mw_AddAccount.setMinimumSize(QtCore.QSize(290, 360))
        mw_AddAccount.setMaximumSize(QtCore.QSize(290, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/favicon/images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mw_AddAccount.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mw_AddAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_AddAccount = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_AddAccount.setMinimumSize(QtCore.QSize(272, 116))
        self.gb_AddAccount.setMaximumSize(QtCore.QSize(272, 116))
        self.gb_AddAccount.setObjectName("gb_AddAccount")
        self.formLayoutWidget = QtWidgets.QWidget(self.gb_AddAccount)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 251, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_UserName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_UserName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_UserName.setObjectName("lbl_UserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_UserName)
        self.le_UserName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_UserName.setObjectName("le_UserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_UserName)
        self.lbl_Password = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Password.setObjectName("lbl_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_Password)
        self.le_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_Password.setObjectName("le_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_Password)
        self.pb_Add = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pb_Add.setObjectName("pb_Add")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pb_Add)
        self.verticalLayout.addWidget(self.gb_AddAccount)
        self.gb_Accounts = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_Accounts.setMinimumSize(QtCore.QSize(270, 220))
        self.gb_Accounts.setMaximumSize(QtCore.QSize(270, 220))
        self.gb_Accounts.setObjectName("gb_Accounts")
        self.listWidget = QtWidgets.QListWidget(self.gb_Accounts)
        self.listWidget.setGeometry(QtCore.QRect(11, 21, 250, 150))
        self.listWidget.setMinimumSize(QtCore.QSize(250, 90))
        self.listWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pb_Delete = QtWidgets.QPushButton(self.gb_Accounts)
        self.pb_Delete.setGeometry(QtCore.QRect(10, 180, 250, 25))
        self.pb_Delete.setObjectName("pb_Delete")
        self.verticalLayout.addWidget(self.gb_Accounts)
        mw_AddAccount.setCentralWidget(self.centralwidget)

        self.retranslateUi(mw_AddAccount)
        QtCore.QMetaObject.connectSlotsByName(mw_AddAccount)

    def retranslateUi(self, mw_AddAccount):
        _translate = QtCore.QCoreApplication.translate
        mw_AddAccount.setWindowTitle(_translate("mw_AddAccount", "Add Account"))
        self.gb_AddAccount.setTitle(_translate("mw_AddAccount", "Add Account"))
        self.lbl_UserName.setText(_translate("mw_AddAccount", "Username:"))
        self.lbl_Password.setText(_translate("mw_AddAccount", "Password:"))
        self.pb_Add.setText(_translate("mw_AddAccount", "Add"))
        self.gb_Accounts.setTitle(_translate("mw_AddAccount", "Accounts"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("mw_AddAccount", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("mw_AddAccount", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("mw_AddAccount", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("mw_AddAccount", "New Item"))
        item = self.listWidget.item(4)
        item.setText(_translate("mw_AddAccount", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pb_Delete.setText(_translate("mw_AddAccount", "Delete"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw_AddAccount = QtWidgets.QMainWindow()
    ui = Ui_mw_AddAccount()
    ui.setupUi(mw_AddAccount)
    mw_AddAccount.show()
    sys.exit(app.exec_())
